# What arrays are allowed to be used for unit tests
ARRAYS:
- {ID: 'unique desc. text', PLUGIN: targetd, PASSWORD: <secret>, URI: 'targetd://admin@fubar'}
- {ID: 'some more desc. and unique text', PLUGIN: targetd, PASSWORD: <secret>, URI: 'targetd://admin@fubar'}

# Where the output of the unit tests should be held
LOGDIR: /tmp/unit

# What is being executed 
PROGRAM: <some program>

# Server and port
SERVER_IP: 'localhost'
SERVER_PORT: 443
PROXY_IS_IP:  True
USE_PROXY: False
PROXY_HOST: 'localhost'
PROXY_PORT: 8080
